config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|pl/ do
    root 'notifications#new'
    resources :notifications, except: [:edit]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
  extend Enumerize
  extend ActiveModel::Naming

  before_create :set_cost_and_term

  enumerize :category, in: %w[accident damage fault], i18n_scope: "category"
  
  validates :description, length: { minimum: 100 }
  validates_email_format_of :email
  validates :category, presence: true

  private

    def set_cost_and_term
      case category.text
      when I18n.t('category.accident')
      	self.term = Time.now + 4.hour
      	  if !Time.now.hour.between?(9, 17)
      	    self.cost = 100
      	  else
      	    self.cost = 50
      	  end
      when I18n.t('category.damage')
      	self.term = Time.now + 1.day
        self.cost = 10
      when I18n.t('category.fault')
      	self.term = Time.now + 3.day
        self.cost = 1
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  private

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
      Rails.application.routes.default_url_options[:locale] = I18n.locale 
    end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: I18n.t('notifications.notice.create') }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: I18n.t('notifications.notice.update') }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: I18n.t('notifications.notice.destroy') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:description, :category, :email, :cost, :term, :read)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ads
    = csrf_meta_tags 
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
  
  %body
    %div.container-fluid
      = link_to_unless I18n.locale == :en, "English", locale: :en 
      |
      = link_to_unless I18n.locale == :pl, "Polski", locale: :pl
      = yield 

app/views/notifications/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@notification) do |f|
  = f.error_notification

  %div.form-group.col-md-5
    = f.input :description, input_html: { class: 'form-control', rows: '3' } 
  %div.form-group.col-md-5
    = f.input :category, input_html: { class: 'form-control' } 
  %div.form-group.col-md-5
    = f.input :email, input_html: { class: 'form-control' }  

  .form-actions
    = f.button :submit, class: "btn btn-primary btn-lg"
    %button= link_to t('cancel'), notifications_path, class: "btn btn-muted btn-lg" 

app/views/notifications/edit.html.haml
%h1 Editing notification

= render 'form'

= link_to 'Show', @notification
\|
= link_to 'Back', notifications_path

app/views/notifications/index.html.haml
%h1.text-center= t('.title')
%div.col-md-10
  %table.table.table-bordered
    %thead
      %tr
        %th= t '.description'
        %th= t '.category'
        %th= t '.email'
        %th= t '.cost'
        %th= t '.term'
        %th 
        %th
        %th

    %tbody
      - @notifications.each do |notification|
        %tr
          %td.scroll= notification.description 
          %td= notification.category
          %td= notification.email
          %td= number_to_currency(notification.cost, unit: "zł", separator: ",", format: "%n %u") 
          %td= notification.term.strftime("%F %H:%M") 
          %td= link_to t('.show'), notification
          %td= link_to t('.edit') # add link to edit if necessary, edit_notification_path(notification)
          %td= link_to t('.destroy'), notification, method: :delete, data: { confirm: 'Are you sure?' }

  %br

  = link_to t('new_notification'), new_notification_path

app/views/notifications/new.html.haml
%h1= t '.title'
= render 'form'

app/views/notifications/show.html.haml
.notice
  %h1= notice

%p
  %b= t('.description')
  = @notification.description
%p
  %b= t('.category')
  = t @notification.category
%p
  %b Email:
  = @notification.email
%p
  %b= t('.cost')
  = number_to_currency(@notification.cost, unit: "PLN", separator: ",", format: "%n %u")
%p
  %b= t('.term')
  = @notification.term.strftime("%F %H:%M") 

= link_to t('new_notification'), new_notification_path
\|
= link_to t('back'), notifications_path